### ISSUE TITLE
High CPU usage when there is no IO active

### ISSUE THREAD

**Issue by pcuzner** [cloudbase/wnbd#98] opened 2023-01-19 23:13 UTC
I'm running inside libvirt based VM's, and noticed that after my test workload completed the CPU was still busy in the W2K19 server and never returns to nominal levels (it's basically consuming a full core all the time)

Here's the job
<pre>
[global]
time_based=1
#directory=c\:\fio
filename=\\.\PHYSICALDRIVE1
numjobs=1
runtime=60
ioengine=windowsaio
ramp_time=10
clocksource=gettimeofday
refill_buffers
direct=1
size=5G
thread=1

[workload]
readwrite=randrw
blocksize=4KB
iodepth=4
rate_iops=45,5
</pre>

And here's a trace through perfmon which shows the period of I/O in blue, and the CPU usage of the rbd-wnbd#1 process in red.
![image](https://user-images.githubusercontent.com/3703087/213582538-a4a814e3-8541-4cba-9f38-f0e8f5cd11f1.png)

This is the version info
<pre>
PS C:\Users\Administrator\Documents\fio> wnbd-client.exe version
wnbd-client.exe: 0.3.1-29-g9a02146
libwnbd.dll: 0.3.1-29-g9a02146
wnbd.sys: 0.3.1-29-g9a02146
</pre>

Any ideas?

**Comment by petrutlucian94** [comment] 2023-01-20 07:15
I think I saw the same issue yesterday while running driver certification tests. In my case, one of the three OSDs crashed right before that (it just ran out of disk space).

I'll reproduce the issue and attach a profiler, Windows Performance Recorder, which should help us pinpoint the issue.

Thanks again for the report.

**Comment by petrutlucian94** [comment] 2023-01-20 13:17
Good news, I've reproduced the issue and it seems to be caused by the recently introduced poll driver. It's calling ``PollDriver::event_wait`` indefinitely, so most probably a return code isn't checked correctly: https://github.com/ceph/ceph/blob/26f55e2064f5be1332e5793dc2418f0a43438bb1/src/msg/async/EventPoll.cc#L160-L191

I'll prepare a fix as soon as possible.

![process_hacker_high_cpu_usage](https://user-images.githubusercontent.com/4570749/213703094-a7968897-d8dc-4084-ab6c-d061eb1b9667.PNG)

**Comment by petrutlucian94** [comment] 2023-02-01 09:36
The Ceph PR merged, I'll go ahead and close this issue. Feel free to reopen it if you still notice unexpectedly high cpu usage.

**Closed by petrutlucian94** 2023-02-01 09:36 UTC

**Comment by pcuzner** [comment] 2023-02-06 23:28
Thanks @petrutlucian94
