### ISSUE TITLE
2TB limit

### ISSUE THREAD

**Issue by Badb0yBadb0y** [cloudbase/wnbd#56] opened 2021-01-28 08:03 UTC
I've managed to mount a drive with this driver but seems like this has a limitation of 2047GB volume.
If I create a 15TB RBD volume when I map it it can just see 1680GB.

What is this limitation? Where is it come from?

Any solution?

**Comment by petrutlucian94** [comment] 2021-01-28 08:10
Hi, thanks for reporting this issue. Due to a mistake, the block count overflows for images larger than 2TB. Luckily we've already fixed that, I'm about to open a Ceph PR today. Here's the fix: https://github.com/petrutlucian94/ceph/commit/973e2a3b91fbe607208b6ab8386946986e1fcce0

This PR will also include a few more RBD related fixes.

Since the problem is on the Ceph side and not caused by WNBD, I'll close this issue.

**Closed** 2021-01-28 08:10 UTC

**Comment by Badb0yBadb0y** [comment] 2021-01-28 15:24
So do I need to build myself a new driver or how can I make it work on my
windows machine?

**Comment by alexpilotti** [comment] 2021-01-28 15:39
@Badb0yBadb0y the CI is building an MSI as we speak, I'll post an update when it's ready

**Comment by alexpilotti** [comment] 2021-01-28 19:20
@Badb0yBadb0y the build job finished, here's the MSI with the latest commits: https://cloudbase.it/downloads/ceph_v16_0_0_beta.msi

**Comment by Badb0yBadb0y** [comment] 2021-01-29 01:41
Awesome work guys, fast and efficient. Let us try.

**Comment by alexpilotti** [comment] 2021-01-29 17:19
Happy to help, please let us know if everything works as expected!

**Comment by Badb0yBadb0y** [comment] 2021-01-30 02:02
Now can see the assigned size, will have a load test from db side soon.
